name: PlayerVaults
main: PlayerVaults\PlayerVaults
api: [3.0.0-ALPHA10]
version: 2.0
commands:
  rucksack:
    default: true
    aliases: ["bp"]
permissions:
  playervaults.vault.1:
    default: true
